In [1]:
import cv2
import os
from random import sample
import pandas as pd

In [2]:
input_dir = './highscore_pictures/'

female = os.listdir(input_dir + 'female/')
male = os.listdir(input_dir + 'male/')

female = list(((i,0) for i in female))
male = list(((i,1) for i in male))

combined = female + male

dfc = pd.DataFrame(combined, columns=["picture", "True Label"])

len(female), len(male)

(50, 50)

In [3]:
dfc = dfc.replace({0:'female',1:'male'})

dfc.head()

              picture True Label
0   female_rank_0.png     female
1   female_rank_1.png     female
2  female_rank_10.png     female
3  female_rank_11.png     female
4  female_rank_12.png     female

In [6]:
combined_test = sample(combined, 50)
mode="Train" #"Test"
labeler="bug_test2"

In [7]:
correct = 0
total = 0
current = 0
log = []
quit = False
folder = ""
labeled = False

cv2.namedWindow("Manual Classification")

for i, l in combined_test:
    
    if(l == 0):
        folder = 'female/'
    else:
        folder = 'male/'
    
    image = cv2.imread(input_dir + folder + i)
    
    h,w,_ = image.shape
    labeled = False
    
    while True:
        cv2.imshow("Manual Classification", image)
        key = cv2.waitKey(1) & 0xFF
        
        if key == ord("f") and not labeled:
            current = 0
            total += 1
            log.append((i,'female'))
            if(current == l):
                correct += 1
            if(mode=="Test"):
                break;
            else:
                labeled = True
                if(current == l):
                    image = cv2.circle(image, ((int) (w/2), (int) (h/2)), ((int) (h/6)), (0,255,0), ((int) (h/24)))
                else:
                    image = cv2.drawMarker(image, ((int) (w/2), (int) (h/2)), (0,0,255), cv2.MARKER_TILTED_CROSS, thickness=32, markerSize=((int) (h/6)))
            
        if key == ord("m") and not labeled:
            current = 1
            total += 1
            log.append((i,'male'))
            if(current == l):
                correct += 1
            if(mode=="Test"):
                break;
            else:
                labeled = True
                if(current == l):
                    image = cv2.circle(image, ((int) (w/2), (int) (h/2)), ((int) (h/6)), (0,255,0), ((int) (h/24)))
                else:
                    image = cv2.drawMarker(image, ((int) (w/2), (int) (h/2)), (0,0,255), cv2.MARKER_TILTED_CROSS, thickness=32, markerSize=((int) (h/6)))
                    
        if key == 32:
            break;
            
        if key == ord("q"):
            quit = True
            break;
            
    if(quit):
        break;
        
cv2.destroyAllWindows()

if(mode == "Test"):
    dfa = pd.DataFrame(log, columns=["picture",labeler])
    dfc[labeler] = dfc['picture'].map(dfa.set_index('picture')[labeler])
        
print("Classified {} out of {} correctly. Accuracy of {} reached.".format(correct, total, correct/total))

Classified 33 out of 50 correctly. Accuracy of 0.66 reached.

In [44]:
dfc

               picture True Label bug_test bug_test2
0    female_rank_0.png     female      NaN       NaN
1    female_rank_1.png     female   female       NaN
2   female_rank_10.png     female      NaN      male
3   female_rank_11.png     female   female      male
4   female_rank_12.png     female   female       NaN
5   female_rank_13.png     female   female      male
6   female_rank_14.png     female      NaN      male
7   female_rank_15.png     female   female      male
8   female_rank_16.png     female      NaN      male
9   female_rank_17.png     female      NaN      male
10  female_rank_18.png     female      NaN       NaN
11  female_rank_19.png     female      NaN       NaN
12   female_rank_2.png     female   female       NaN
13  female_rank_20.png     female      NaN      male
14  female_rank_21.png     female   female       NaN
15  female_rank_22.png     female   female       NaN
16  female_rank_23.png     female      NaN       NaN
17  female_rank_24.png     female      NaN       NaN
18  female_rank_25.png     female      NaN      male
19  female_rank_26.png     female   female       NaN
20  female_rank_27.png     female      NaN      male
21  female_rank_28.png     female      NaN       NaN
22  female_rank_29.png     female   female       NaN
23   female_rank_3.png     female   female       NaN
24  female_rank_30.png     female      NaN       NaN
25  female_rank_31.png     female      NaN       NaN
26  female_rank_32.png     female   female      male
27  female_rank_33.png     female   female      male
28  female_rank_34.png     female   female       NaN
29  female_rank_35.png     female   female       NaN
..                 ...        ...      ...       ...
70    male_rank_26.png       male      NaN       NaN
71    male_rank_27.png       male      NaN      male
72    male_rank_28.png       male      NaN      male
73    male_rank_29.png       male   female      male
74     male_rank_3.png       male      NaN      male
75    male_rank_30.png       male   female       NaN
76    male_rank_31.png       male   female       NaN
77    male_rank_32.png       male      NaN      male
78    male_rank_33.png       male      NaN       NaN
79    male_rank_34.png       male   female      male
80    male_rank_35.png       male   female       NaN
81    male_rank_36.png       male   female      male
82    male_rank_37.png       male      NaN       NaN
83    male_rank_38.png       male   female       NaN
84    male_rank_39.png       male   female      male
85     male_rank_4.png       male      NaN      male
86    male_rank_40.png       male      NaN      male
87    male_rank_41.png       male   female      male
88    male_rank_42.png       male      NaN       NaN
89    male_rank_43.png       male   female      male
90    male_rank_44.png       male      NaN       NaN
91    male_rank_46.png       male      NaN       NaN
92    male_rank_47.png       male      NaN      male
93    male_rank_48.png       male   female      male
94    male_rank_49.png       male   female      male
95     male_rank_5.png       male      NaN      male
96     male_rank_6.png       male   female      male
97     male_rank_7.png       male   female      male
98     male_rank_8.png       male      NaN       NaN
99     male_rank_9.png       male      NaN      male

[100 rows x 4 columns]

In [ ]:
dfc.to_pickle("./manual_labels.pkl")